gamma: 0.98
actor_lr: 0.001
critic_lr: 0.001
batch_size: 64
actor_mlp_widths: [128, 128]
critic_mlp_widths: [128, 128]
value_function_train_iterations: 80
normalise_advantages: True
trajectories_per_epoch: 30