gamma: 0.99
clip_parameter: 0.1
actor_lr: 0.0003
critic_lr: 0.0003
batch_size: 64
actor_mlp_widths: [128, 128]
critic_mlp_widths: [128, 128]
policy_train_iterations: 60
value_function_train_iterations: 60
normalise_advantages: True
trajectories_per_epoch: 20